### ISSUE TITLE
Firebase / initializeApp()

### ISSUE THREAD

**Issue by arturjnt** [KenAragorn/create_flutter_provider_app#16]
Hello,

First of all, thank you for the code, it can have a lot of value.

That being said, I found some issues when trying to start the app.

First I had to go to `pubspec.yaml` and do:

```yaml 
  assets:
    - assets/lang/en.json
    - assets/lang/zh.json
 
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
        - asset: assets/fonts/Product-Sans-Italic.ttf
          style: italic
        - asset: assets/fonts/Product-Sans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Product-Sans-Bold-Italic.ttf
          style: italic
          weight: 700
```
and change line 27 on the `app_localizations.dart` to
```dart
await rootBundle.loadString('assets/lang/${locale.languageCode}.json');
```
or the app wouldn't even start.

Then I had to add 
```dart
await Firebase.initializeApp();
```
between lines 15/16 of the main.dart and main_prod.dart, or again, the app wouldn't even start. (Also had to add `firebase_core: ^1.6.0` to the `pubspec.yaml`, and the import to `main.dart` and and `main_prod.dart` of course).

Then in line 81 of the `my_app.dart` I had to change it to:
```dart
return userSnapshot.data?.uid != 'null'
  ? HomeScreen()
  : SignInScreen();
```
because `userSnapshot.hasData` always had "something", and that was causing records to be inserted in the database with `uid as null` meaning `/user/null/todos/<todo_item_id>`.

But now I can't move on.

### The issue itself is when I log out and login with another user, **I have the data from the old user**.
I know you say on the `README.md` that:

> To achieve this, FirestoreDatabase will be re-created everytime onAuthStateChanged changed.

But this doesn't seem to be happening.

Might be due to my changes as mentioned above.

Any help would be much appreciated. Regards to all.
